### ISSUE TITLE
System Interface Design

### ISSUE THREAD

**Issue by wdan** [HKUST-VISLab/vismooc-front-end#3]
For vismooc, a brand new user interface is needed.
The new UI should satisfy these requirements:
1. 
2. 
3.

**Comment by chenzhutian** [comment]
I think we could have an index page of vismooc.
In the index page, there should be some features introduction, video tutorial, and fancy demo.
Some examples:
1. [Vscode](code.visualstudio.com)
![image](https://cloud.githubusercontent.com/assets/3315274/19916845/fa25a608-a0f8-11e6-9d73-b0687ffbf38c.png)
2.[Typescript](https://www.typescriptlang.org/)
![image](https://cloud.githubusercontent.com/assets/3315274/19916925/9683879a-a0f9-11e6-96c4-2e447957c521.png)

3.[Docker](https://www.docker.com)
![image](https://cloud.githubusercontent.com/assets/3315274/19916930/a7b29e3e-a0f9-11e6-919f-7b554f5b36e7.png)

**Comment by chenzhutian** [comment]
After user logging, we could have another dashboard page to provide some charts and manipulation for users.

**Comment by chenzhutian** [comment]
A dashborad example
![image](https://cloud.githubusercontent.com/assets/3315274/20004042/e40a17fa-a2c4-11e6-86f7-8d79726e2da1.png)

**Comment by chenzhutian** [comment]
tabs:
- course
- video
- forum

**Comment by chenzhutian** [comment]
A dragable grid demo.
